FROM python:latest

RUN mkdir -p /usr/src/app

COPY scripts /usr/src/app/scripts
COPY tables /usr/src/app/tables
COPY Makefile /usr/src/app/Makefile
COPY requirements.txt /usr/src/app/requirements.txt
COPY requirements-dev.txt /usr/src/app/requirements-dev.txt
WORKDIR /usr/src/app
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-dev.txt